export const ADD_TO_CART = 'ADD_TO_CART';
export const MINUS_FROM_CART = 'MINUS_FROM_CART';
export const REMOVE_FROM_CART = 'DELETE_FROM_CART';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';

export const CHANGE_SIZE_FILTER_PRODUCTS = 'CHANGE_SIZE_FILTER_PRODUCTS';
export const CHANGE_PRICE_FILTER_PRODUCTS = 'CHANGE_PRICE_FILTER_PRODUCTS';